inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringConcatenation:
  Mode: conservative

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'